### ISSUE TITLE
Debug output

### ISSUE THREAD

**Issue by ghost** [MaxCDN/perl-maxcdn#1]
Hi

I noticed in the source there is a mention of the word `debug`

How can I turn this on? It would be nice to know what the script is doing in the background, and to see if it's doing its job correctly.

**Comment by idabic** [comment]
Hello,

Sure thing. Basically, passing "1" after a call you are making you will request debug output. For example:
my $data = $api->get("/users.json", 1);

Important thing to mention, debugging is yet to be updated for all methods. I'll probably use the same method of invoking (passing the "1").

**Comment by ghost** [comment]
Thanks
